// Code generated by Kitex v0.5.2. DO NOT EDIT.

package payservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	pay "pay/kitex_gen/pay"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	BuyGoods(ctx context.Context, request *pay.BuyGoodsReq, callOptions ...callopt.Option) (r *pay.NilResponse, err error)
	CallBack(ctx context.Context, request *pay.CallBackReq, callOptions ...callopt.Option) (r *pay.NilResponse, err error)
	Notify(ctx context.Context, request *pay.NotifyReq, callOptions ...callopt.Option) (r *pay.NilResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kPayServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPayServiceClient struct {
	*kClient
}

func (p *kPayServiceClient) BuyGoods(ctx context.Context, request *pay.BuyGoodsReq, callOptions ...callopt.Option) (r *pay.NilResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BuyGoods(ctx, request)
}

func (p *kPayServiceClient) CallBack(ctx context.Context, request *pay.CallBackReq, callOptions ...callopt.Option) (r *pay.NilResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CallBack(ctx, request)
}

func (p *kPayServiceClient) Notify(ctx context.Context, request *pay.NotifyReq, callOptions ...callopt.Option) (r *pay.NilResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Notify(ctx, request)
}
